msm8937-common: libshims: Make shim for libui
P: GraphicBuffer::lock(uint32_t inUsage, void** vaddr);
Q: GraphicBuffer::lock(uint32_t inUsage, void** vaddr, int32_t* outBytesPerPixel = nullptr, int32_t* outBytesPerStride = nullptr);
Error: cannot locate symbol "_ZN7android13GraphicBuffer4lockEjPPv"

[SebaUbuntu] Move to Android.bp